name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build the Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: ghcr.io/webteamchesh/nuxttest:${{ github.run_number }}

    - name: Docker push
      run: docker push ghcr.io/webteamchesh/nuxttest:${{ github.run_number }}
  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Sleep for 15 seconds
      run: sleep 15s
      shell: bash
    - name: Contensis block push action
      uses: contensis/block-push@v1
      with:
        block-id: nuxttest
        alias: chesheast
        project-id: blockstest
        image-uri: ghcr.io/webteamchesh/nuxttest:${{ github.run_number }}
        client-id: ${{ secrets.CLIENT_ID }}
        shared-secret: ${{ secrets.SHARED_SECRET }}
        git-token: ${{ secrets.GITHUB_TOKEN }}
   
